//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace ozgurtek.framework.common.Data.Format.Wms
{ // 
  // This source code was auto-generated by xsd, Version=4.0.30319.18020.
  // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class WMS_Capabilities
    {

        private Service serviceField;

        private Capability capabilityField;

        private string versionField;

        private string updateSequenceField;

        public WMS_Capabilities()
        {
            this.versionField = "1.3.0";
        }

        /// <remarks/>
        public Service Service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }

        /// <remarks/>
        public Capability Capability
        {
            get
            {
                return this.capabilityField;
            }
            set
            {
                this.capabilityField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string updateSequence
        {
            get
            {
                return this.updateSequenceField;
            }
            set
            {
                this.updateSequenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class Service
    {

        private ServiceName nameField;

        private string titleField;

        private string abstractField;

        private Keyword[] keywordListField;

        private OnlineResource onlineResourceField;

        private ContactInformation contactInformationField;

        private string feesField;

        private string accessConstraintsField;

        private string layerLimitField;

        private string maxWidthField;

        private string maxHeightField;

        /// <remarks/>
        public ServiceName Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string Abstract
        {
            get
            {
                return this.abstractField;
            }
            set
            {
                this.abstractField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("Keyword", IsNullable = false)]
        public Keyword[] KeywordList
        {
            get
            {
                return this.keywordListField;
            }
            set
            {
                this.keywordListField = value;
            }
        }

        /// <remarks/>
        public OnlineResource OnlineResource
        {
            get
            {
                return this.onlineResourceField;
            }
            set
            {
                this.onlineResourceField = value;
            }
        }

        /// <remarks/>
        public ContactInformation ContactInformation
        {
            get
            {
                return this.contactInformationField;
            }
            set
            {
                this.contactInformationField = value;
            }
        }

        /// <remarks/>
        public string Fees
        {
            get
            {
                return this.feesField;
            }
            set
            {
                this.feesField = value;
            }
        }

        /// <remarks/>
        public string AccessConstraints
        {
            get
            {
                return this.accessConstraintsField;
            }
            set
            {
                this.accessConstraintsField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "positiveInteger")]
        public string LayerLimit
        {
            get
            {
                return this.layerLimitField;
            }
            set
            {
                this.layerLimitField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "positiveInteger")]
        public string MaxWidth
        {
            get
            {
                return this.maxWidthField;
            }
            set
            {
                this.maxWidthField = value;
            }
        }

        /// <remarks/>
        [XmlElement(DataType = "positiveInteger")]
        public string MaxHeight
        {
            get
            {
                return this.maxHeightField;
            }
            set
            {
                this.maxHeightField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    public enum ServiceName
    {

        /// <remarks/>
        WMS,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class Keyword
    {

        private string vocabularyField;

        private string valueField;

        /// <remarks/>
        [XmlAttribute()]
        public string vocabulary
        {
            get
            {
                return this.vocabularyField;
            }
            set
            {
                this.vocabularyField = value;
            }
        }

        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class OnlineResource
    {
        private string hrefField;
        private string typeField;

        public OnlineResource()
        {
            this.typeField = "simple";
        }

        [XmlAttribute("href", Namespace = "http://www.w3.org/1999/xlink")]
        public string Href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }

        [XmlAttribute("type", Namespace = "http://www.w3.org/1999/xlink")]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class ContactInformation
    {

        private ContactPersonPrimary contactPersonPrimaryField;

        private string contactPositionField;

        private ContactAddress contactAddressField;

        private string contactVoiceTelephoneField;

        private string contactFacsimileTelephoneField;

        private string contactElectronicMailAddressField;

        /// <remarks/>
        public ContactPersonPrimary ContactPersonPrimary
        {
            get
            {
                return this.contactPersonPrimaryField;
            }
            set
            {
                this.contactPersonPrimaryField = value;
            }
        }

        /// <remarks/>
        public string ContactPosition
        {
            get
            {
                return this.contactPositionField;
            }
            set
            {
                this.contactPositionField = value;
            }
        }

        /// <remarks/>
        public ContactAddress ContactAddress
        {
            get
            {
                return this.contactAddressField;
            }
            set
            {
                this.contactAddressField = value;
            }
        }

        /// <remarks/>
        public string ContactVoiceTelephone
        {
            get
            {
                return this.contactVoiceTelephoneField;
            }
            set
            {
                this.contactVoiceTelephoneField = value;
            }
        }

        /// <remarks/>
        public string ContactFacsimileTelephone
        {
            get
            {
                return this.contactFacsimileTelephoneField;
            }
            set
            {
                this.contactFacsimileTelephoneField = value;
            }
        }

        /// <remarks/>
        public string ContactElectronicMailAddress
        {
            get
            {
                return this.contactElectronicMailAddressField;
            }
            set
            {
                this.contactElectronicMailAddressField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class ContactPersonPrimary
    {

        private string contactPersonField;

        private string contactOrganizationField;

        /// <remarks/>
        public string ContactPerson
        {
            get
            {
                return this.contactPersonField;
            }
            set
            {
                this.contactPersonField = value;
            }
        }

        /// <remarks/>
        public string ContactOrganization
        {
            get
            {
                return this.contactOrganizationField;
            }
            set
            {
                this.contactOrganizationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class ContactAddress
    {

        private string addressTypeField;

        private string addressField;

        private string cityField;

        private string stateOrProvinceField;

        private string postCodeField;

        private string countryField;

        /// <remarks/>
        public string AddressType
        {
            get
            {
                return this.addressTypeField;
            }
            set
            {
                this.addressTypeField = value;
            }
        }

        /// <remarks/>
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string StateOrProvince
        {
            get
            {
                return this.stateOrProvinceField;
            }
            set
            {
                this.stateOrProvinceField = value;
            }
        }

        /// <remarks/>
        public string PostCode
        {
            get
            {
                return this.postCodeField;
            }
            set
            {
                this.postCodeField = value;
            }
        }

        /// <remarks/>
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class Capability
    {

        private Request requestField;

        private string[] exceptionField;

        private object[] _ExtendedCapabilitiesField;

        private Layer layerField;

        /// <remarks/>
        public Request Request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("Format", IsNullable = false)]
        public string[] Exception
        {
            get
            {
                return this.exceptionField;
            }
            set
            {
                this.exceptionField = value;
            }
        }

        /// <remarks/>
        [XmlElement("_ExtendedCapabilities")]
        public object[] _ExtendedCapabilities
        {
            get
            {
                return this._ExtendedCapabilitiesField;
            }
            set
            {
                this._ExtendedCapabilitiesField = value;
            }
        }

        /// <remarks/>
        public Layer Layer
        {
            get
            {
                return this.layerField;
            }
            set
            {
                this.layerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class Request
    {

        private OperationType getCapabilitiesField;

        private OperationType getMapField;

        private OperationType getFeatureInfoField;

        private OperationType describeLayerField;

        private OperationType[] _ExtendedOperationField;

        /// <remarks/>
        public OperationType GetCapabilities
        {
            get
            {
                return this.getCapabilitiesField;
            }
            set
            {
                this.getCapabilitiesField = value;
            }
        }

        /// <remarks/>
        public OperationType GetMap
        {
            get
            {
                return this.getMapField;
            }
            set
            {
                this.getMapField = value;
            }
        }

        /// <remarks/>
        public OperationType GetFeatureInfo
        {
            get
            {
                return this.getFeatureInfoField;
            }
            set
            {
                this.getFeatureInfoField = value;
            }
        }

        /// <remarks/>
        public OperationType DescribeLayer
        {
            get
            {
                return this.describeLayerField;
            }
            set
            {
                this.describeLayerField = value;
            }
        }

        /// <remarks/>
        [XmlElement("_ExtendedOperation")]
        public OperationType[] _ExtendedOperation
        {
            get
            {
                return this._ExtendedOperationField;
            }
            set
            {
                this._ExtendedOperationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://www.opengis.net/wms")]
    [XmlRoot("GetCapabilities", Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class OperationType
    {

        private string[] formatField;

        private DCPType[] dCPTypeField;

        /// <remarks/>
        [XmlElement("Format")]
        public string[] Format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }

        /// <remarks/>
        [XmlElement("DCPType")]
        public DCPType[] DCPType
        {
            get
            {
                return this.dCPTypeField;
            }
            set
            {
                this.dCPTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class DCPType
    {

        private HTTP hTTPField;

        /// <remarks/>
        public HTTP HTTP
        {
            get
            {
                return this.hTTPField;
            }
            set
            {
                this.hTTPField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class HTTP
    {

        private Get getField;

        private Post postField;

        /// <remarks/>
        public Get Get
        {
            get
            {
                return this.getField;
            }
            set
            {
                this.getField = value;
            }
        }

        /// <remarks/>
        public Post Post
        {
            get
            {
                return this.postField;
            }
            set
            {
                this.postField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class Get
    {

        private OnlineResource onlineResourceField;

        /// <remarks/>
        public OnlineResource OnlineResource
        {
            get
            {
                return this.onlineResourceField;
            }
            set
            {
                this.onlineResourceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class Post
    {

        private OnlineResource onlineResourceField;

        /// <remarks/>
        public OnlineResource OnlineResource
        {
            get
            {
                return this.onlineResourceField;
            }
            set
            {
                this.onlineResourceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class Layer
    {

        private string nameField;

        private string titleField;

        private string abstractField;

        private Keyword[] keywordListField;

        private string[] cRSField;

        private EX_GeographicBoundingBox eX_GeographicBoundingBoxField;

        private BoundingBox[] boundingBoxField;

        private Dimension[] dimensionField;

        private Attribution attributionField;

        private AuthorityURL[] authorityURLField;

        private Identifier[] identifierField;

        private MetadataURL[] metadataURLField;

        private DataURL[] dataURLField;

        private FeatureListURL[] featureListURLField;

        private Style[] styleField;

        private double minScaleDenominatorField;

        private bool minScaleDenominatorFieldSpecified;

        private double maxScaleDenominatorField;

        private bool maxScaleDenominatorFieldSpecified;

        private Layer[] layer1Field;

        private bool queryableField;

        private string cascadedField;

        private bool opaqueField;

        private bool noSubsetsField;

        private string fixedWidthField;

        private string fixedHeightField;

        public Layer()
        {
            this.queryableField = false;
            this.opaqueField = false;
            this.noSubsetsField = false;
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string Abstract
        {
            get
            {
                return this.abstractField;
            }
            set
            {
                this.abstractField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("Keyword", IsNullable = false)]
        public Keyword[] KeywordList
        {
            get
            {
                return this.keywordListField;
            }
            set
            {
                this.keywordListField = value;
            }
        }

        /// <remarks/>
        [XmlElement("CRS")]
        public string[] CRS
        {
            get
            {
                return this.cRSField;
            }
            set
            {
                this.cRSField = value;
            }
        }

        /// <remarks/>
        public EX_GeographicBoundingBox EX_GeographicBoundingBox
        {
            get
            {
                return this.eX_GeographicBoundingBoxField;
            }
            set
            {
                this.eX_GeographicBoundingBoxField = value;
            }
        }

        /// <remarks/>
        [XmlElement("BoundingBox")]
        public BoundingBox[] BoundingBox
        {
            get
            {
                return this.boundingBoxField;
            }
            set
            {
                this.boundingBoxField = value;
            }
        }

        /// <remarks/>
        [XmlElement("Dimension")]
        public Dimension[] Dimension
        {
            get
            {
                return this.dimensionField;
            }
            set
            {
                this.dimensionField = value;
            }
        }

        /// <remarks/>
        public Attribution Attribution
        {
            get
            {
                return this.attributionField;
            }
            set
            {
                this.attributionField = value;
            }
        }

        /// <remarks/>
        [XmlElement("AuthorityURL")]
        public AuthorityURL[] AuthorityURL
        {
            get
            {
                return this.authorityURLField;
            }
            set
            {
                this.authorityURLField = value;
            }
        }

        /// <remarks/>
        [XmlElement("Identifier")]
        public Identifier[] Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        /// <remarks/>
        [XmlElement("MetadataURL")]
        public MetadataURL[] MetadataURL
        {
            get
            {
                return this.metadataURLField;
            }
            set
            {
                this.metadataURLField = value;
            }
        }

        /// <remarks/>
        [XmlElement("DataURL")]
        public DataURL[] DataURL
        {
            get
            {
                return this.dataURLField;
            }
            set
            {
                this.dataURLField = value;
            }
        }

        /// <remarks/>
        [XmlElement("FeatureListURL")]
        public FeatureListURL[] FeatureListURL
        {
            get
            {
                return this.featureListURLField;
            }
            set
            {
                this.featureListURLField = value;
            }
        }

        /// <remarks/>
        [XmlElement("Style")]
        public Style[] Style
        {
            get
            {
                return this.styleField;
            }
            set
            {
                this.styleField = value;
            }
        }

        /// <remarks/>
        public double MinScaleDenominator
        {
            get
            {
                return this.minScaleDenominatorField;
            }
            set
            {
                this.minScaleDenominatorField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool MinScaleDenominatorSpecified
        {
            get
            {
                return this.minScaleDenominatorFieldSpecified;
            }
            set
            {
                this.minScaleDenominatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        public double MaxScaleDenominator
        {
            get
            {
                return this.maxScaleDenominatorField;
            }
            set
            {
                this.maxScaleDenominatorField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool MaxScaleDenominatorSpecified
        {
            get
            {
                return this.maxScaleDenominatorFieldSpecified;
            }
            set
            {
                this.maxScaleDenominatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement("Layer")]
        public Layer[] Layer1
        {
            get
            {
                return this.layer1Field;
            }
            set
            {
                this.layer1Field = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool queryable
        {
            get
            {
                return this.queryableField;
            }
            set
            {
                this.queryableField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "nonNegativeInteger")]
        public string cascaded
        {
            get
            {
                return this.cascadedField;
            }
            set
            {
                this.cascadedField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool opaque
        {
            get
            {
                return this.opaqueField;
            }
            set
            {
                this.opaqueField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool noSubsets
        {
            get
            {
                return this.noSubsetsField;
            }
            set
            {
                this.noSubsetsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "nonNegativeInteger")]
        public string fixedWidth
        {
            get
            {
                return this.fixedWidthField;
            }
            set
            {
                this.fixedWidthField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "nonNegativeInteger")]
        public string fixedHeight
        {
            get
            {
                return this.fixedHeightField;
            }
            set
            {
                this.fixedHeightField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class EX_GeographicBoundingBox
    {

        private double westBoundLongitudeField;

        private double eastBoundLongitudeField;

        private double southBoundLatitudeField;

        private double northBoundLatitudeField;

        /// <remarks/>
        public double westBoundLongitude
        {
            get
            {
                return this.westBoundLongitudeField;
            }
            set
            {
                this.westBoundLongitudeField = value;
            }
        }

        /// <remarks/>
        public double eastBoundLongitude
        {
            get
            {
                return this.eastBoundLongitudeField;
            }
            set
            {
                this.eastBoundLongitudeField = value;
            }
        }

        /// <remarks/>
        public double southBoundLatitude
        {
            get
            {
                return this.southBoundLatitudeField;
            }
            set
            {
                this.southBoundLatitudeField = value;
            }
        }

        /// <remarks/>
        public double northBoundLatitude
        {
            get
            {
                return this.northBoundLatitudeField;
            }
            set
            {
                this.northBoundLatitudeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class BoundingBox
    {

        private string cRSField;

        private double minxField;

        private double minyField;

        private double maxxField;

        private double maxyField;

        private double resxField;

        private bool resxFieldSpecified;

        private double resyField;

        private bool resyFieldSpecified;

        /// <remarks/>
        [XmlAttribute()]
        public string CRS
        {
            get
            {
                return this.cRSField;
            }
            set
            {
                this.cRSField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public double minx
        {
            get
            {
                return this.minxField;
            }
            set
            {
                this.minxField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public double miny
        {
            get
            {
                return this.minyField;
            }
            set
            {
                this.minyField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public double maxx
        {
            get
            {
                return this.maxxField;
            }
            set
            {
                this.maxxField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public double maxy
        {
            get
            {
                return this.maxyField;
            }
            set
            {
                this.maxyField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public double resx
        {
            get
            {
                return this.resxField;
            }
            set
            {
                this.resxField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool resxSpecified
        {
            get
            {
                return this.resxFieldSpecified;
            }
            set
            {
                this.resxFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public double resy
        {
            get
            {
                return this.resyField;
            }
            set
            {
                this.resyField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool resySpecified
        {
            get
            {
                return this.resyFieldSpecified;
            }
            set
            {
                this.resyFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class Dimension
    {

        private string nameField;

        private string unitsField;

        private string unitSymbolField;

        private string defaultField;

        private bool multipleValuesField;

        private bool multipleValuesFieldSpecified;

        private bool nearestValueField;

        private bool nearestValueFieldSpecified;

        private bool currentField;

        private bool currentFieldSpecified;

        private string valueField;

        /// <remarks/>
        [XmlAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string unitSymbol
        {
            get
            {
                return this.unitSymbolField;
            }
            set
            {
                this.unitSymbolField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string @default
        {
            get
            {
                return this.defaultField;
            }
            set
            {
                this.defaultField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool multipleValues
        {
            get
            {
                return this.multipleValuesField;
            }
            set
            {
                this.multipleValuesField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool multipleValuesSpecified
        {
            get
            {
                return this.multipleValuesFieldSpecified;
            }
            set
            {
                this.multipleValuesFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool nearestValue
        {
            get
            {
                return this.nearestValueField;
            }
            set
            {
                this.nearestValueField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool nearestValueSpecified
        {
            get
            {
                return this.nearestValueFieldSpecified;
            }
            set
            {
                this.nearestValueFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool current
        {
            get
            {
                return this.currentField;
            }
            set
            {
                this.currentField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool currentSpecified
        {
            get
            {
                return this.currentFieldSpecified;
            }
            set
            {
                this.currentFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class Attribution
    {

        private string titleField;

        private OnlineResource onlineResourceField;

        private LogoURL logoURLField;

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public OnlineResource OnlineResource
        {
            get
            {
                return this.onlineResourceField;
            }
            set
            {
                this.onlineResourceField = value;
            }
        }

        /// <remarks/>
        public LogoURL LogoURL
        {
            get
            {
                return this.logoURLField;
            }
            set
            {
                this.logoURLField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class LogoURL
    {

        private string formatField;

        private OnlineResource onlineResourceField;

        private string widthField;

        private string heightField;

        /// <remarks/>
        public string Format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }

        /// <remarks/>
        public OnlineResource OnlineResource
        {
            get
            {
                return this.onlineResourceField;
            }
            set
            {
                this.onlineResourceField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "positiveInteger")]
        public string width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "positiveInteger")]
        public string height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class AuthorityURL
    {

        private OnlineResource onlineResourceField;

        private string nameField;

        /// <remarks/>
        public OnlineResource OnlineResource
        {
            get
            {
                return this.onlineResourceField;
            }
            set
            {
                this.onlineResourceField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class Identifier
    {

        private string authorityField;

        private string valueField;

        /// <remarks/>
        [XmlAttribute()]
        public string authority
        {
            get
            {
                return this.authorityField;
            }
            set
            {
                this.authorityField = value;
            }
        }

        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class MetadataURL
    {

        private string formatField;

        private OnlineResource onlineResourceField;

        private string typeField;

        /// <remarks/>
        public string Format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }

        /// <remarks/>
        public OnlineResource OnlineResource
        {
            get
            {
                return this.onlineResourceField;
            }
            set
            {
                this.onlineResourceField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "NMTOKEN")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class DataURL
    {

        private string formatField;

        private OnlineResource onlineResourceField;

        /// <remarks/>
        public string Format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }

        /// <remarks/>
        public OnlineResource OnlineResource
        {
            get
            {
                return this.onlineResourceField;
            }
            set
            {
                this.onlineResourceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class FeatureListURL
    {

        private string formatField;

        private OnlineResource onlineResourceField;

        /// <remarks/>
        public string Format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }

        /// <remarks/>
        public OnlineResource OnlineResource
        {
            get
            {
                return this.onlineResourceField;
            }
            set
            {
                this.onlineResourceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class Style
    {

        private string nameField;

        private string titleField;

        private string abstractField;

        private LegendURL[] legendURLField;

        private StyleSheetURL styleSheetURLField;

        private StyleURL styleURLField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string Abstract
        {
            get
            {
                return this.abstractField;
            }
            set
            {
                this.abstractField = value;
            }
        }

        /// <remarks/>
        [XmlElement("LegendURL")]
        public LegendURL[] LegendURL
        {
            get
            {
                return this.legendURLField;
            }
            set
            {
                this.legendURLField = value;
            }
        }

        /// <remarks/>
        public StyleSheetURL StyleSheetURL
        {
            get
            {
                return this.styleSheetURLField;
            }
            set
            {
                this.styleSheetURLField = value;
            }
        }

        /// <remarks/>
        public StyleURL StyleURL
        {
            get
            {
                return this.styleURLField;
            }
            set
            {
                this.styleURLField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class LegendURL
    {

        private string formatField;

        private OnlineResource onlineResourceField;

        private string widthField;

        private string heightField;

        /// <remarks/>
        public string Format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }

        /// <remarks/>
        public OnlineResource OnlineResource
        {
            get
            {
                return this.onlineResourceField;
            }
            set
            {
                this.onlineResourceField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "positiveInteger")]
        public string width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute(DataType = "positiveInteger")]
        public string height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class StyleSheetURL
    {

        private string formatField;

        private OnlineResource onlineResourceField;

        /// <remarks/>
        public string Format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }

        /// <remarks/>
        public OnlineResource OnlineResource
        {
            get
            {
                return this.onlineResourceField;
            }
            set
            {
                this.onlineResourceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class StyleURL
    {

        private string formatField;

        private OnlineResource onlineResourceField;

        /// <remarks/>
        public string Format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }

        /// <remarks/>
        public OnlineResource OnlineResource
        {
            get
            {
                return this.onlineResourceField;
            }
            set
            {
                this.onlineResourceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class KeywordList
    {

        private Keyword[] keywordField;

        /// <remarks/>
        [XmlElement("Keyword")]
        public Keyword[] Keyword
        {
            get
            {
                return this.keywordField;
            }
            set
            {
                this.keywordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://www.opengis.net/wms")]
    [XmlRoot(Namespace = "http://www.opengis.net/wms", IsNullable = false)]
    public partial class Exception : System.Exception
    {

        private string[] formatField;

        /// <remarks/>
        [XmlElement("Format")]
        public string[] Format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }
    }
}
